id: I264F5815
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-31T06:51:30+00:00'
last_modified: '2022-06-08T17:12:00.453784+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG11880
  title: རྗེ་བཙུན་དམ་པ་དབྱངས་ཅན་བཟང་པོས་ཉེ་བར་སྩལ་བའི་རླུང་སེམས་དབྱེར་མེད་ཀྱི་ཁྲིད།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    2A43:
      image_group_id: I1KG11897
      title: ''
      total_pages: 636
      order: 1
      base_file: 2A43.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
