id: P010742
initial_creation_type: ocr
created_at: 31/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W1KG11880
  title: རྗེ་བཙུན་དམ་པ་དབྱངས་ཅན་བཟང་པོས་ཉེ་བར་སྩལ་བའི་རླུང་སེམས་དབྱེར་མེད་ཀྱི་ཁྲིད།
  author: ''
  volumes:
    47c336059b0e479d9961a1da507850b8:
      image_group_id: I1KG11897
      title: ''
      volume_number: 1
      total_pages: 636
      base_file: v001.txt
